name: Build Site
on:
  workflow_call:
    inputs:
      create-artifact:
        description: 'Should create artifact of build'
        required: false
        type: boolean
        default: false
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-site:
    name: Build Static Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Create Artifact
        if: ${{ inputs.create-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: built-site
          path: public/
