name: Deploy Static Pages
on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-site:
    concurrency: ci-${{ github.ref }}
    uses: ./.github/workflows/build-site.yml
    with:
      create-artifact: true

  deploy-site:
    needs: build-site

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: built-site

      - name: Deploy Static Site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
