name: Pull Request Testing
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dry-build:
    name: Create Dry Build
    uses: ./.github/workflows/build-site.yml
